### ISSUE TITLE
!commit plugin

### ISSUE THREAD

**Issue by edunham** [hamperbot/meta#13]
Writing commit messages is hard. Hamper should help us. 

Just the front page of http://whatthecommit.com/ should do it. Maybe the occasional answer from https://twitter.com/sadserver as well, just for variety.

**Comment by tschuy** [comment]
Tentatively thinking of doing this this weekend.

**Comment by edunham** [comment]
Mythmon fixed this in https://github.com/hamperbot/hamper-lug/commit/329a3efb9e9f196368dea346cc230c1df5ba0a82
